docker run -it \
--env "APPDYNAMICS_AGENT_ACCOUNT_NAME=customer1" \
--env "APPDYNAMICS_CONTROLLER_SSL_ENABLED=false" \
--env "APPDYNAMICS_CONTROLLER_HOST_NAME=my-controller" \
--env "APPDYNAMICS_CONTROLLER_PORT=80" \
--env "APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=$1" \
--env "APPDYNAMICS_AGENT_TIER_NAME=SimpleBootApp" \
--env "APPDYNAMICS_AGENT_APPLICATION_NAME=SimpleBootApp" \
--env "APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME=true" \
--env "APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX=SimpleBootApp" \
jholmes/simpleboot:latest